FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY ["ProjectAtlas.Api.csproj", "./"]
RUN dotnet restore "./ProjectAtlas.Api.csproj"

COPY . .

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--project", "ProjectAtlas.Api.csproj", "--urls", "http://0.0.0.0:8080"]