POST http://localhost:5177/profiles/
Content-Type: application/json

{
    "guid": "bd7100da-46a3-4db3-bfb5-28c534ad2be9",
    "name": "John Doe",
    "email": "john.doe@example.com"
}


###
GET http://localhost:5177/profiles/bd7100da-46a3-4db3-bfb5-28c534ad2be9
Content-Type: application/json

###
DELETE http://localhost:5177/profiles/bd7100da-46a3-4db3-bfb5-28c534ad2be9
Content-Type: application/json

