@HostAddress = http://localhost:5177
@AccessToken = eyJhbGciOiJFUzI1NiIsImtpZCI6IjEwMDdiN2I5LTY3NWYtNDM5Ni05NmRlLWM3MmM2ZDcwNjMxNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FjdXVic3VzbGZidnV6ZnF5dGZtLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiZDcxMDBkYS00NmEzLTRkYjMtYmZiNS0yOGM1MzRhZDJiZTkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NzQ4MTI3LCJpYXQiOjE3NzQ3NDQ1MjcsImVtYWlsIjoiZHJld3NoYWt1bGFAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzQ3NDQ1Mjd9XSwic2Vzc2lvbl9pZCI6ImRmMDEyYjY4LWY3ZTktNDcxYS1iNjRkLTljMDM2ODhmNGYxYiIsImlzX2Fub255bW91cyI6ZmFsc2V9.-ZPPY4GFVv5XRJ-r4PbjhOK-7GFLxq9n5sVjsD9WeSZle6U9vO_c5WKZSSbxJAgZki0U9CQjRcGTfzHBQMa-qg
@SupabaseAuthUrl = https://acuubsuslfbvuzfqytfm.supabase.co/auth/v1
@SupabaseApiKey = sb_publishable_j_EkTvkf0bOcV6A3AQgWAg_Znuo_pQm

POST {{HostAddress}}/profiles/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name": "Drewmba Hrewmba",
    "email": "drewshakula@gmail.com"
}

###
GET {{HostAddress}}/profiles/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###
GET {{HostAddress}}/profiles/bd7100da-46a3-4db3-bfb5-28c534ad2be9
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###
DELETE {{HostAddress}}/profiles/bd7100da-46a3-4db3-bfb5-28c534ad2be9
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###
PUT {{HostAddress}}/profiles/bd7100da-46a3-4db3-bfb5-28c534ad2be9
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name": "John Doe Update123d",
    "email": "drewshakula@gmail.com"
}

###
POST {{SupabaseAuthUrl}}/token?grant_type=password
ApiKey: {{SupabaseApiKey}}
Content-Type: application/json

{
    "email": "drewshakula@gmail.com",
    "password": "123"
}